const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
const LOGIN_ERROR = 'LOGIN_ERROR';
const USER_REQUEST = 'USER_REQUEST';

export const STATUS = {
  LOGIN_SUCCESS,
  LOGOUT_REQUEST,
  LOGIN_ERROR,
  USER_REQUEST,
};
